
// This file has been generated by the GUI designer. Do not modify.
namespace BioGorod.Dialogs.Client
{
	public partial class CounterpartyDlg
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button buttonSave;
		
		private global::Gtk.Button buttonCancel;
		
		private global::QSFNS.GetOrgInfo getorginfo1;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.HBox hbox19;
		
		private global::Gtk.RadioButton radioInfo;
		
		private global::Gtk.RadioButton radioContacts;
		
		private global::Gtk.RadioButton radioDetails;
		
		private global::Gtk.RadioButton radioContactPersons;
		
		private global::Gtk.RadioButton radioContracts;
		
		private global::Gtk.RadioButton radioDeliveryPoint;
		
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow4;
		
		private global::Gtk.Table table1;
		
		private global::Gamma.Widgets.yEnumComboBox comboDocumentsDelivery;
		
		private global::Gamma.GtkWidgets.yEntry entryFullName;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow6;
		
		private global::Gamma.GtkWidgets.yTextView dataComment;
		
		private global::Gtk.HBox hbox13;
		
		private global::Gamma.GtkWidgets.yCheckButton ycheckIsArchived;
		
		private global::Gamma.GtkWidgets.yCheckButton checkHaveArbitration;
		
		private global::Gamma.GtkWidgets.yCheckButton checkRequirePrepayment;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Label label31;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.Label labelFullName;
		
		private global::Gtk.Label labelShort;
		
		private global::Gamma.Widgets.yEntryReference referencePaymentManager;
		
		private global::Gtk.VBox vboxCooperation;
		
		private global::Gamma.GtkWidgets.yCheckButton checkCustomer;
		
		private global::Gamma.GtkWidgets.yCheckButton checkSupplier;
		
		private global::Gamma.GtkWidgets.yCheckButton checkPartner;
		
		private global::Gamma.GtkWidgets.yEntry yentryName;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Table datatable2;
		
		private global::QSContacts.EmailsView emailsView;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.Button buttonActualFromLegal;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.Button buttonDocFromLegal;
		
		private global::Gtk.Button buttonDocFromActual;
		
		private global::QSOsm.JsonAddressEntry jsonaddressActual;
		
		private global::QSOsm.JsonAddressEntry jsonaddressDocDelivery;
		
		private global::QSOsm.JsonAddressEntry jsonaddressLegal;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.Label label18;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Label label8;
		
		private global::QSContacts.PhonesView phonesView;
		
		private global::Gtk.Label label33;
		
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.Table datatable4;
		
		private global::Gtk.Label label34;
		
		private global::Gtk.Label label35;
		
		private global::Gtk.Label label36;
		
		private global::Gtk.Label label37;
		
		private global::Gtk.Label label38;
		
		private global::Gtk.Label label39;
		
		private global::Gamma.Widgets.yValidatedEntry validatedentryOGRN;
		
		private global::Gamma.Widgets.yValidatedEntry validatedINN;
		
		private global::Gamma.Widgets.yValidatedEntry validatedKPP;
		
		private global::Gamma.GtkWidgets.yEntry yentrySignBaseOf;
		
		private global::Gamma.GtkWidgets.yEntry yentrySignFIO;
		
		private global::Gamma.GtkWidgets.yEntry yentrySignPost;
		
		private global::QSBanks.AccountsView accountsView;
		
		private global::Gtk.Label label40;
		
		private global::BioGorod.Dialogs.Client.CounterpartyContactsView contactsview1;
		
		private global::Gtk.Label label42;
		
		private global::BioGorod.Dialogs.Client.CounterpartyContractsView counterpartyContractsView;
		
		private global::Gtk.Label label44;
		
		private global::Gtk.VBox vbox9;
		
		private global::BioGorod.Dialogs.Client.CounterpartyAddressesView deliveryPointView;
		
		private global::Gtk.Label label46;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BioGorod.Dialogs.Client.CounterpartyDlg
			global::Stetic.BinContainer.Attach (this);
			this.Name = "BioGorod.Dialogs.Client.CounterpartyDlg";
			// Container child BioGorod.Dialogs.Client.CounterpartyDlg.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.HeightRequest = 400;
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(6));
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonSave = new global::Gtk.Button ();
			this.buttonSave.CanFocus = true;
			this.buttonSave.Name = "buttonSave";
			this.buttonSave.UseUnderline = true;
			this.buttonSave.Label = global::Mono.Unix.Catalog.GetString ("Сохранить");
			global::Gtk.Image w1 = new global::Gtk.Image ();
			w1.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-floppy", global::Gtk.IconSize.Menu);
			this.buttonSave.Image = w1;
			this.hbox1.Add (this.buttonSave);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonSave]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString ("Отмена");
			global::Gtk.Image w3 = new global::Gtk.Image ();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-revert-to-saved", global::Gtk.IconSize.Menu);
			this.buttonCancel.Image = w3;
			this.hbox1.Add (this.buttonCancel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonCancel]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.getorginfo1 = new global::QSFNS.GetOrgInfo ();
			this.getorginfo1.Events = ((global::Gdk.EventMask)(256));
			this.getorginfo1.Name = "getorginfo1";
			this.hbox1.Add (this.getorginfo1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.getorginfo1]));
			w5.Position = 2;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox2.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator1]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox19 = new global::Gtk.HBox ();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.radioInfo = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Информация"));
			this.radioInfo.CanFocus = true;
			this.radioInfo.Name = "radioInfo";
			this.radioInfo.DrawIndicator = false;
			this.radioInfo.UseUnderline = true;
			this.radioInfo.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.hbox19.Add (this.radioInfo);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.radioInfo]));
			w8.Position = 0;
			// Container child hbox19.Gtk.Box+BoxChild
			this.radioContacts = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Контакты"));
			this.radioContacts.CanFocus = true;
			this.radioContacts.Name = "radioContacts";
			this.radioContacts.DrawIndicator = false;
			this.radioContacts.UseUnderline = true;
			this.radioContacts.Group = this.radioInfo.Group;
			this.hbox19.Add (this.radioContacts);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.radioContacts]));
			w9.Position = 1;
			// Container child hbox19.Gtk.Box+BoxChild
			this.radioDetails = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Реквизиты"));
			this.radioDetails.CanFocus = true;
			this.radioDetails.Name = "radioDetails";
			this.radioDetails.DrawIndicator = false;
			this.radioDetails.UseUnderline = true;
			this.radioDetails.Group = this.radioInfo.Group;
			this.hbox19.Add (this.radioDetails);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.radioDetails]));
			w10.Position = 2;
			// Container child hbox19.Gtk.Box+BoxChild
			this.radioContactPersons = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Контактные лица"));
			this.radioContactPersons.CanFocus = true;
			this.radioContactPersons.Name = "radioContactPersons";
			this.radioContactPersons.DrawIndicator = false;
			this.radioContactPersons.UseUnderline = true;
			this.radioContactPersons.Group = this.radioInfo.Group;
			this.hbox19.Add (this.radioContactPersons);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.radioContactPersons]));
			w11.Position = 3;
			// Container child hbox19.Gtk.Box+BoxChild
			this.radioContracts = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Договоры"));
			this.radioContracts.CanFocus = true;
			this.radioContracts.Name = "radioContracts";
			this.radioContracts.DrawIndicator = false;
			this.radioContracts.UseUnderline = true;
			this.radioContracts.Group = this.radioInfo.Group;
			this.hbox19.Add (this.radioContracts);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.radioContracts]));
			w12.Position = 4;
			// Container child hbox19.Gtk.Box+BoxChild
			this.radioDeliveryPoint = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Адреса объектов"));
			this.radioDeliveryPoint.CanFocus = true;
			this.radioDeliveryPoint.Name = "radioDeliveryPoint";
			this.radioDeliveryPoint.DrawIndicator = false;
			this.radioDeliveryPoint.UseUnderline = true;
			this.radioDeliveryPoint.Group = this.radioInfo.Group;
			this.hbox19.Add (this.radioDeliveryPoint);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.radioDeliveryPoint]));
			w13.Position = 5;
			this.vbox2.Add (this.hbox19);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox19]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
			this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
			global::Gtk.Viewport w15 = new global::Gtk.Viewport ();
			w15.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(6)), ((uint)(4)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.table1.BorderWidth = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.comboDocumentsDelivery = new global::Gamma.Widgets.yEnumComboBox ();
			this.comboDocumentsDelivery.Name = "comboDocumentsDelivery";
			this.comboDocumentsDelivery.ShowSpecialStateAll = false;
			this.comboDocumentsDelivery.ShowSpecialStateNot = false;
			this.comboDocumentsDelivery.UseShortTitle = false;
			this.comboDocumentsDelivery.DefaultFirst = true;
			this.table1.Add (this.comboDocumentsDelivery);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.comboDocumentsDelivery]));
			w16.TopAttach = ((uint)(3));
			w16.BottomAttach = ((uint)(4));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryFullName = new global::Gamma.GtkWidgets.yEntry ();
			this.entryFullName.CanFocus = true;
			this.entryFullName.Name = "entryFullName";
			this.entryFullName.IsEditable = true;
			this.entryFullName.MaxLength = 300;
			this.entryFullName.InvisibleChar = '●';
			this.table1.Add (this.entryFullName);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryFullName]));
			w17.TopAttach = ((uint)(1));
			w17.BottomAttach = ((uint)(2));
			w17.LeftAttach = ((uint)(1));
			w17.RightAttach = ((uint)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.GtkScrolledWindow6 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow6.Name = "GtkScrolledWindow6";
			this.GtkScrolledWindow6.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow6.Gtk.Container+ContainerChild
			this.dataComment = new global::Gamma.GtkWidgets.yTextView ();
			this.dataComment.CanFocus = true;
			this.dataComment.Name = "dataComment";
			this.GtkScrolledWindow6.Add (this.dataComment);
			this.table1.Add (this.GtkScrolledWindow6);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1 [this.GtkScrolledWindow6]));
			w19.TopAttach = ((uint)(5));
			w19.BottomAttach = ((uint)(6));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(4));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox13 = new global::Gtk.HBox ();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.ycheckIsArchived = new global::Gamma.GtkWidgets.yCheckButton ();
			this.ycheckIsArchived.TooltipMarkup = "Больше не работаем с этим клиентом";
			this.ycheckIsArchived.CanFocus = true;
			this.ycheckIsArchived.Name = "ycheckIsArchived";
			this.ycheckIsArchived.Label = global::Mono.Unix.Catalog.GetString ("Архивный");
			this.ycheckIsArchived.DrawIndicator = true;
			this.ycheckIsArchived.UseUnderline = true;
			this.hbox13.Add (this.ycheckIsArchived);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.ycheckIsArchived]));
			w20.Position = 0;
			w20.Expand = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.checkHaveArbitration = new global::Gamma.GtkWidgets.yCheckButton ();
			this.checkHaveArbitration.CanFocus = true;
			this.checkHaveArbitration.Name = "checkHaveArbitration";
			this.checkHaveArbitration.Label = global::Mono.Unix.Catalog.GetString ("Есть арбитражные дела");
			this.checkHaveArbitration.DrawIndicator = true;
			this.checkHaveArbitration.UseUnderline = true;
			this.hbox13.Add (this.checkHaveArbitration);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.checkHaveArbitration]));
			w21.Position = 1;
			w21.Expand = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.checkRequirePrepayment = new global::Gamma.GtkWidgets.yCheckButton ();
			this.checkRequirePrepayment.CanFocus = true;
			this.checkRequirePrepayment.Name = "checkRequirePrepayment";
			this.checkRequirePrepayment.Label = global::Mono.Unix.Catalog.GetString ("Обязательна предоплата");
			this.checkRequirePrepayment.DrawIndicator = true;
			this.checkRequirePrepayment.UseUnderline = true;
			this.hbox13.Add (this.checkRequirePrepayment);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.checkRequirePrepayment]));
			w22.Position = 2;
			w22.Expand = false;
			this.table1.Add (this.hbox13);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox13]));
			w23.TopAttach = ((uint)(2));
			w23.BottomAttach = ((uint)(3));
			w23.LeftAttach = ((uint)(1));
			w23.RightAttach = ((uint)(4));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 1F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Как отправляем документы:");
			this.table1.Add (this.label3);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1 [this.label3]));
			w24.TopAttach = ((uint)(3));
			w24.BottomAttach = ((uint)(4));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label31 = new global::Gtk.Label ();
			this.label31.Name = "label31";
			this.label31.Xalign = 1F;
			this.label31.Yalign = 0F;
			this.label31.LabelProp = global::Mono.Unix.Catalog.GetString ("Комментарий:");
			this.label31.Justify = ((global::Gtk.Justification)(1));
			this.table1.Add (this.label31);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1 [this.label31]));
			w25.TopAttach = ((uint)(5));
			w25.BottomAttach = ((uint)(6));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Ответственный за контроль оплаты:");
			this.table1.Add (this.label4);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table1 [this.label4]));
			w26.TopAttach = ((uint)(4));
			w26.BottomAttach = ((uint)(5));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.Xalign = 1F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Тип контрагента:");
			this.table1.Add (this.label9);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table1 [this.label9]));
			w27.TopAttach = ((uint)(3));
			w27.BottomAttach = ((uint)(4));
			w27.LeftAttach = ((uint)(2));
			w27.RightAttach = ((uint)(3));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelFullName = new global::Gtk.Label ();
			this.labelFullName.Name = "labelFullName";
			this.labelFullName.Xalign = 1F;
			this.labelFullName.LabelProp = global::Mono.Unix.Catalog.GetString ("Полное наименование:");
			this.table1.Add (this.labelFullName);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelFullName]));
			w28.TopAttach = ((uint)(1));
			w28.BottomAttach = ((uint)(2));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelShort = new global::Gtk.Label ();
			this.labelShort.Name = "labelShort";
			this.labelShort.Xalign = 1F;
			this.labelShort.LabelProp = global::Mono.Unix.Catalog.GetString ("Наименование:");
			this.table1.Add (this.labelShort);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelShort]));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.referencePaymentManager = new global::Gamma.Widgets.yEntryReference ();
			this.referencePaymentManager.Events = ((global::Gdk.EventMask)(256));
			this.referencePaymentManager.Name = "referencePaymentManager";
			this.table1.Add (this.referencePaymentManager);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table1 [this.referencePaymentManager]));
			w30.TopAttach = ((uint)(4));
			w30.BottomAttach = ((uint)(5));
			w30.LeftAttach = ((uint)(1));
			w30.RightAttach = ((uint)(2));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.vboxCooperation = new global::Gtk.VBox ();
			this.vboxCooperation.Name = "vboxCooperation";
			this.vboxCooperation.Spacing = 1;
			// Container child vboxCooperation.Gtk.Box+BoxChild
			this.checkCustomer = new global::Gamma.GtkWidgets.yCheckButton ();
			this.checkCustomer.CanFocus = true;
			this.checkCustomer.Name = "checkCustomer";
			this.checkCustomer.Label = global::Mono.Unix.Catalog.GetString ("Покупатель");
			this.checkCustomer.DrawIndicator = true;
			this.checkCustomer.UseUnderline = true;
			this.vboxCooperation.Add (this.checkCustomer);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vboxCooperation [this.checkCustomer]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vboxCooperation.Gtk.Box+BoxChild
			this.checkSupplier = new global::Gamma.GtkWidgets.yCheckButton ();
			this.checkSupplier.CanFocus = true;
			this.checkSupplier.Name = "checkSupplier";
			this.checkSupplier.Label = global::Mono.Unix.Catalog.GetString ("Поставщик");
			this.checkSupplier.DrawIndicator = true;
			this.checkSupplier.UseUnderline = true;
			this.vboxCooperation.Add (this.checkSupplier);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vboxCooperation [this.checkSupplier]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vboxCooperation.Gtk.Box+BoxChild
			this.checkPartner = new global::Gamma.GtkWidgets.yCheckButton ();
			this.checkPartner.CanFocus = true;
			this.checkPartner.Name = "checkPartner";
			this.checkPartner.Label = global::Mono.Unix.Catalog.GetString ("Партнер");
			this.checkPartner.DrawIndicator = true;
			this.checkPartner.UseUnderline = true;
			this.vboxCooperation.Add (this.checkPartner);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vboxCooperation [this.checkPartner]));
			w33.Position = 2;
			w33.Expand = false;
			w33.Fill = false;
			this.table1.Add (this.vboxCooperation);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table1 [this.vboxCooperation]));
			w34.TopAttach = ((uint)(3));
			w34.BottomAttach = ((uint)(5));
			w34.LeftAttach = ((uint)(3));
			w34.RightAttach = ((uint)(4));
			w34.XOptions = ((global::Gtk.AttachOptions)(4));
			w34.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table1.Gtk.Table+TableChild
			this.yentryName = new global::Gamma.GtkWidgets.yEntry ();
			this.yentryName.CanFocus = true;
			this.yentryName.Name = "yentryName";
			this.yentryName.IsEditable = true;
			this.yentryName.InvisibleChar = '●';
			this.table1.Add (this.yentryName);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table1 [this.yentryName]));
			w35.LeftAttach = ((uint)(1));
			w35.RightAttach = ((uint)(4));
			w35.XOptions = ((global::Gtk.AttachOptions)(4));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			w15.Add (this.table1);
			this.GtkScrolledWindow4.Add (w15);
			this.notebook1.Add (this.GtkScrolledWindow4);
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Информация");
			this.notebook1.SetTabLabel (this.GtkScrolledWindow4, this.label2);
			this.label2.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.datatable2 = new global::Gtk.Table (((uint)(5)), ((uint)(3)), false);
			this.datatable2.Name = "datatable2";
			this.datatable2.RowSpacing = ((uint)(6));
			this.datatable2.ColumnSpacing = ((uint)(6));
			this.datatable2.BorderWidth = ((uint)(6));
			// Container child datatable2.Gtk.Table+TableChild
			this.emailsView = new global::QSContacts.EmailsView ();
			this.emailsView.Events = ((global::Gdk.EventMask)(256));
			this.emailsView.Name = "emailsView";
			this.datatable2.Add (this.emailsView);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.emailsView]));
			w39.TopAttach = ((uint)(1));
			w39.BottomAttach = ((uint)(2));
			w39.LeftAttach = ((uint)(1));
			w39.RightAttach = ((uint)(3));
			w39.XOptions = ((global::Gtk.AttachOptions)(4));
			w39.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable2.Gtk.Table+TableChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.buttonActualFromLegal = new global::Gtk.Button ();
			this.buttonActualFromLegal.TooltipMarkup = "Скопировать из юридического адреса.";
			this.buttonActualFromLegal.CanFocus = true;
			this.buttonActualFromLegal.Name = "buttonActualFromLegal";
			this.buttonActualFromLegal.UseUnderline = true;
			this.buttonActualFromLegal.Label = global::Mono.Unix.Catalog.GetString ("Как юридический");
			this.hbox7.Add (this.buttonActualFromLegal);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.buttonActualFromLegal]));
			w40.Position = 0;
			w40.Expand = false;
			w40.Fill = false;
			this.datatable2.Add (this.hbox7);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.hbox7]));
			w41.TopAttach = ((uint)(3));
			w41.BottomAttach = ((uint)(4));
			w41.LeftAttach = ((uint)(2));
			w41.RightAttach = ((uint)(3));
			w41.XOptions = ((global::Gtk.AttachOptions)(4));
			w41.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child datatable2.Gtk.Table+TableChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.buttonDocFromLegal = new global::Gtk.Button ();
			this.buttonDocFromLegal.TooltipMarkup = "Скопировать из юридического адреса.";
			this.buttonDocFromLegal.CanFocus = true;
			this.buttonDocFromLegal.Name = "buttonDocFromLegal";
			this.buttonDocFromLegal.UseUnderline = true;
			this.buttonDocFromLegal.Label = global::Mono.Unix.Catalog.GetString ("Как юридический");
			this.hbox8.Add (this.buttonDocFromLegal);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.buttonDocFromLegal]));
			w42.Position = 0;
			w42.Expand = false;
			w42.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.buttonDocFromActual = new global::Gtk.Button ();
			this.buttonDocFromActual.TooltipMarkup = "Скопировать из физического адреса.";
			this.buttonDocFromActual.CanFocus = true;
			this.buttonDocFromActual.Name = "buttonDocFromActual";
			this.buttonDocFromActual.UseUnderline = true;
			this.buttonDocFromActual.Label = global::Mono.Unix.Catalog.GetString ("Как физический");
			this.hbox8.Add (this.buttonDocFromActual);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.buttonDocFromActual]));
			w43.Position = 1;
			w43.Expand = false;
			w43.Fill = false;
			this.datatable2.Add (this.hbox8);
			global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.hbox8]));
			w44.TopAttach = ((uint)(4));
			w44.BottomAttach = ((uint)(5));
			w44.LeftAttach = ((uint)(2));
			w44.RightAttach = ((uint)(3));
			w44.XOptions = ((global::Gtk.AttachOptions)(4));
			w44.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child datatable2.Gtk.Table+TableChild
			this.jsonaddressActual = new global::QSOsm.JsonAddressEntry ();
			this.jsonaddressActual.Events = ((global::Gdk.EventMask)(256));
			this.jsonaddressActual.Name = "jsonaddressActual";
			this.datatable2.Add (this.jsonaddressActual);
			global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.jsonaddressActual]));
			w45.TopAttach = ((uint)(3));
			w45.BottomAttach = ((uint)(4));
			w45.LeftAttach = ((uint)(1));
			w45.RightAttach = ((uint)(2));
			w45.XOptions = ((global::Gtk.AttachOptions)(4));
			w45.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable2.Gtk.Table+TableChild
			this.jsonaddressDocDelivery = new global::QSOsm.JsonAddressEntry ();
			this.jsonaddressDocDelivery.Events = ((global::Gdk.EventMask)(256));
			this.jsonaddressDocDelivery.Name = "jsonaddressDocDelivery";
			this.datatable2.Add (this.jsonaddressDocDelivery);
			global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.jsonaddressDocDelivery]));
			w46.TopAttach = ((uint)(4));
			w46.BottomAttach = ((uint)(5));
			w46.LeftAttach = ((uint)(1));
			w46.RightAttach = ((uint)(2));
			w46.XOptions = ((global::Gtk.AttachOptions)(4));
			w46.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable2.Gtk.Table+TableChild
			this.jsonaddressLegal = new global::QSOsm.JsonAddressEntry ();
			this.jsonaddressLegal.Events = ((global::Gdk.EventMask)(256));
			this.jsonaddressLegal.Name = "jsonaddressLegal";
			this.datatable2.Add (this.jsonaddressLegal);
			global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.jsonaddressLegal]));
			w47.TopAttach = ((uint)(2));
			w47.BottomAttach = ((uint)(3));
			w47.LeftAttach = ((uint)(1));
			w47.RightAttach = ((uint)(2));
			w47.XOptions = ((global::Gtk.AttachOptions)(4));
			w47.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable2.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xalign = 1F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Общий e-mail:");
			this.datatable2.Add (this.label11);
			global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.label11]));
			w48.TopAttach = ((uint)(1));
			w48.BottomAttach = ((uint)(2));
			w48.XOptions = ((global::Gtk.AttachOptions)(4));
			w48.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable2.Gtk.Table+TableChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.Xalign = 1F;
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Общие телефоны:");
			this.datatable2.Add (this.label18);
			global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.label18]));
			w49.XOptions = ((global::Gtk.AttachOptions)(4));
			w49.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable2.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 1F;
			this.label5.Yalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Юридический адрес:");
			this.datatable2.Add (this.label5);
			global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.label5]));
			w50.TopAttach = ((uint)(2));
			w50.BottomAttach = ((uint)(3));
			w50.XOptions = ((global::Gtk.AttachOptions)(4));
			w50.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable2.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 1F;
			this.label6.Yalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Фактический адрес:");
			this.datatable2.Add (this.label6);
			global::Gtk.Table.TableChild w51 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.label6]));
			w51.TopAttach = ((uint)(3));
			w51.BottomAttach = ((uint)(4));
			w51.XOptions = ((global::Gtk.AttachOptions)(4));
			w51.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable2.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.Xalign = 1F;
			this.label8.Yalign = 0F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Адрес доставки документов:");
			this.datatable2.Add (this.label8);
			global::Gtk.Table.TableChild w52 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.label8]));
			w52.TopAttach = ((uint)(4));
			w52.BottomAttach = ((uint)(5));
			w52.XOptions = ((global::Gtk.AttachOptions)(4));
			w52.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable2.Gtk.Table+TableChild
			this.phonesView = new global::QSContacts.PhonesView ();
			this.phonesView.Events = ((global::Gdk.EventMask)(256));
			this.phonesView.Name = "phonesView";
			this.datatable2.Add (this.phonesView);
			global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.phonesView]));
			w53.LeftAttach = ((uint)(1));
			w53.RightAttach = ((uint)(3));
			w53.XOptions = ((global::Gtk.AttachOptions)(4));
			w53.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook1.Add (this.datatable2);
			global::Gtk.Notebook.NotebookChild w54 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.datatable2]));
			w54.Position = 1;
			// Notebook tab
			this.label33 = new global::Gtk.Label ();
			this.label33.Name = "label33";
			this.label33.LabelProp = global::Mono.Unix.Catalog.GetString ("Контакты");
			this.notebook1.SetTabLabel (this.datatable2, this.label33);
			this.label33.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			this.vbox6.BorderWidth = ((uint)(6));
			// Container child vbox6.Gtk.Box+BoxChild
			this.datatable4 = new global::Gtk.Table (((uint)(3)), ((uint)(4)), false);
			this.datatable4.Name = "datatable4";
			this.datatable4.RowSpacing = ((uint)(6));
			this.datatable4.ColumnSpacing = ((uint)(6));
			// Container child datatable4.Gtk.Table+TableChild
			this.label34 = new global::Gtk.Label ();
			this.label34.Name = "label34";
			this.label34.Xalign = 1F;
			this.label34.LabelProp = global::Mono.Unix.Catalog.GetString ("На основании:");
			this.datatable4.Add (this.label34);
			global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.label34]));
			w55.TopAttach = ((uint)(2));
			w55.BottomAttach = ((uint)(3));
			w55.LeftAttach = ((uint)(2));
			w55.RightAttach = ((uint)(3));
			w55.XOptions = ((global::Gtk.AttachOptions)(4));
			w55.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.label35 = new global::Gtk.Label ();
			this.label35.Name = "label35";
			this.label35.Xalign = 1F;
			this.label35.LabelProp = global::Mono.Unix.Catalog.GetString ("ОГРН:");
			this.datatable4.Add (this.label35);
			global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.label35]));
			w56.TopAttach = ((uint)(2));
			w56.BottomAttach = ((uint)(3));
			w56.XOptions = ((global::Gtk.AttachOptions)(4));
			w56.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.label36 = new global::Gtk.Label ();
			this.label36.Name = "label36";
			this.label36.Xalign = 1F;
			this.label36.LabelProp = global::Mono.Unix.Catalog.GetString ("КПП:");
			this.datatable4.Add (this.label36);
			global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.label36]));
			w57.TopAttach = ((uint)(1));
			w57.BottomAttach = ((uint)(2));
			w57.XOptions = ((global::Gtk.AttachOptions)(4));
			w57.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.label37 = new global::Gtk.Label ();
			this.label37.Name = "label37";
			this.label37.Xalign = 1F;
			this.label37.LabelProp = global::Mono.Unix.Catalog.GetString ("ИНН:");
			this.datatable4.Add (this.label37);
			global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.label37]));
			w58.XOptions = ((global::Gtk.AttachOptions)(4));
			w58.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.label38 = new global::Gtk.Label ();
			this.label38.Name = "label38";
			this.label38.Xalign = 1F;
			this.label38.LabelProp = global::Mono.Unix.Catalog.GetString ("В лице:");
			this.datatable4.Add (this.label38);
			global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.label38]));
			w59.TopAttach = ((uint)(1));
			w59.BottomAttach = ((uint)(2));
			w59.LeftAttach = ((uint)(2));
			w59.RightAttach = ((uint)(3));
			w59.XOptions = ((global::Gtk.AttachOptions)(4));
			w59.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.label39 = new global::Gtk.Label ();
			this.label39.Name = "label39";
			this.label39.Xalign = 1F;
			this.label39.LabelProp = global::Mono.Unix.Catalog.GetString ("ФИО для договора:");
			this.datatable4.Add (this.label39);
			global::Gtk.Table.TableChild w60 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.label39]));
			w60.LeftAttach = ((uint)(2));
			w60.RightAttach = ((uint)(3));
			w60.XOptions = ((global::Gtk.AttachOptions)(4));
			w60.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.validatedentryOGRN = new global::Gamma.Widgets.yValidatedEntry ();
			this.validatedentryOGRN.CanFocus = true;
			this.validatedentryOGRN.Name = "validatedentryOGRN";
			this.validatedentryOGRN.IsEditable = true;
			this.validatedentryOGRN.MaxLength = 13;
			this.validatedentryOGRN.InvisibleChar = '●';
			this.datatable4.Add (this.validatedentryOGRN);
			global::Gtk.Table.TableChild w61 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.validatedentryOGRN]));
			w61.TopAttach = ((uint)(2));
			w61.BottomAttach = ((uint)(3));
			w61.LeftAttach = ((uint)(1));
			w61.RightAttach = ((uint)(2));
			w61.XOptions = ((global::Gtk.AttachOptions)(4));
			w61.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.validatedINN = new global::Gamma.Widgets.yValidatedEntry ();
			this.validatedINN.CanFocus = true;
			this.validatedINN.Name = "validatedINN";
			this.validatedINN.IsEditable = true;
			this.validatedINN.MaxLength = 12;
			this.validatedINN.InvisibleChar = '●';
			this.datatable4.Add (this.validatedINN);
			global::Gtk.Table.TableChild w62 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.validatedINN]));
			w62.LeftAttach = ((uint)(1));
			w62.RightAttach = ((uint)(2));
			w62.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.validatedKPP = new global::Gamma.Widgets.yValidatedEntry ();
			this.validatedKPP.CanFocus = true;
			this.validatedKPP.Name = "validatedKPP";
			this.validatedKPP.IsEditable = true;
			this.validatedKPP.MaxLength = 9;
			this.validatedKPP.InvisibleChar = '●';
			this.datatable4.Add (this.validatedKPP);
			global::Gtk.Table.TableChild w63 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.validatedKPP]));
			w63.TopAttach = ((uint)(1));
			w63.BottomAttach = ((uint)(2));
			w63.LeftAttach = ((uint)(1));
			w63.RightAttach = ((uint)(2));
			w63.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.yentrySignBaseOf = new global::Gamma.GtkWidgets.yEntry ();
			this.yentrySignBaseOf.CanFocus = true;
			this.yentrySignBaseOf.Name = "yentrySignBaseOf";
			this.yentrySignBaseOf.IsEditable = true;
			this.yentrySignBaseOf.InvisibleChar = '●';
			this.datatable4.Add (this.yentrySignBaseOf);
			global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.yentrySignBaseOf]));
			w64.TopAttach = ((uint)(2));
			w64.BottomAttach = ((uint)(3));
			w64.LeftAttach = ((uint)(3));
			w64.RightAttach = ((uint)(4));
			w64.XOptions = ((global::Gtk.AttachOptions)(4));
			w64.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.yentrySignFIO = new global::Gamma.GtkWidgets.yEntry ();
			this.yentrySignFIO.CanFocus = true;
			this.yentrySignFIO.Name = "yentrySignFIO";
			this.yentrySignFIO.IsEditable = true;
			this.yentrySignFIO.InvisibleChar = '●';
			this.datatable4.Add (this.yentrySignFIO);
			global::Gtk.Table.TableChild w65 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.yentrySignFIO]));
			w65.LeftAttach = ((uint)(3));
			w65.RightAttach = ((uint)(4));
			w65.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.yentrySignPost = new global::Gamma.GtkWidgets.yEntry ();
			this.yentrySignPost.CanFocus = true;
			this.yentrySignPost.Name = "yentrySignPost";
			this.yentrySignPost.IsEditable = true;
			this.yentrySignPost.InvisibleChar = '●';
			this.datatable4.Add (this.yentrySignPost);
			global::Gtk.Table.TableChild w66 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.yentrySignPost]));
			w66.TopAttach = ((uint)(1));
			w66.BottomAttach = ((uint)(2));
			w66.LeftAttach = ((uint)(3));
			w66.RightAttach = ((uint)(4));
			w66.XOptions = ((global::Gtk.AttachOptions)(4));
			w66.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox6.Add (this.datatable4);
			global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.datatable4]));
			w67.Position = 0;
			w67.Expand = false;
			w67.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.accountsView = new global::QSBanks.AccountsView ();
			this.accountsView.Events = ((global::Gdk.EventMask)(256));
			this.accountsView.Name = "accountsView";
			this.vbox6.Add (this.accountsView);
			global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.accountsView]));
			w68.Position = 1;
			this.notebook1.Add (this.vbox6);
			global::Gtk.Notebook.NotebookChild w69 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox6]));
			w69.Position = 2;
			// Notebook tab
			this.label40 = new global::Gtk.Label ();
			this.label40.Name = "label40";
			this.label40.LabelProp = global::Mono.Unix.Catalog.GetString ("Реквизиты");
			this.notebook1.SetTabLabel (this.vbox6, this.label40);
			this.label40.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.contactsview1 = new global::BioGorod.Dialogs.Client.CounterpartyContactsView ();
			this.contactsview1.Events = ((global::Gdk.EventMask)(256));
			this.contactsview1.Name = "contactsview1";
			this.notebook1.Add (this.contactsview1);
			global::Gtk.Notebook.NotebookChild w70 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.contactsview1]));
			w70.Position = 3;
			// Notebook tab
			this.label42 = new global::Gtk.Label ();
			this.label42.Name = "label42";
			this.label42.LabelProp = global::Mono.Unix.Catalog.GetString ("Контактные лица");
			this.notebook1.SetTabLabel (this.contactsview1, this.label42);
			this.label42.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.counterpartyContractsView = new global::BioGorod.Dialogs.Client.CounterpartyContractsView ();
			this.counterpartyContractsView.Events = ((global::Gdk.EventMask)(256));
			this.counterpartyContractsView.Name = "counterpartyContractsView";
			this.notebook1.Add (this.counterpartyContractsView);
			global::Gtk.Notebook.NotebookChild w71 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.counterpartyContractsView]));
			w71.Position = 4;
			// Notebook tab
			this.label44 = new global::Gtk.Label ();
			this.label44.Name = "label44";
			this.label44.LabelProp = global::Mono.Unix.Catalog.GetString ("Договор");
			this.notebook1.SetTabLabel (this.counterpartyContractsView, this.label44);
			this.label44.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			this.vbox9.BorderWidth = ((uint)(6));
			// Container child vbox9.Gtk.Box+BoxChild
			this.deliveryPointView = new global::BioGorod.Dialogs.Client.CounterpartyAddressesView ();
			this.deliveryPointView.Events = ((global::Gdk.EventMask)(256));
			this.deliveryPointView.Name = "deliveryPointView";
			this.vbox9.Add (this.deliveryPointView);
			global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.deliveryPointView]));
			w72.Position = 0;
			this.notebook1.Add (this.vbox9);
			global::Gtk.Notebook.NotebookChild w73 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox9]));
			w73.Position = 5;
			// Notebook tab
			this.label46 = new global::Gtk.Label ();
			this.label46.Name = "label46";
			this.label46.LabelProp = global::Mono.Unix.Catalog.GetString ("Точки доставки");
			this.notebook1.SetTabLabel (this.vbox9, this.label46);
			this.label46.ShowAll ();
			this.vbox2.Add (this.notebook1);
			global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.notebook1]));
			w74.Position = 3;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonSave.Clicked += new global::System.EventHandler (this.OnButtonSaveClicked);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
			this.getorginfo1.FillButtonCliked += new global::System.EventHandler (this.OnGetorginfo1FillButtonCliked);
			this.radioInfo.Toggled += new global::System.EventHandler (this.OnRadioInfoToggled);
			this.radioContacts.Toggled += new global::System.EventHandler (this.OnRadioContactsToggled);
			this.radioDetails.Toggled += new global::System.EventHandler (this.OnRadioDetailsToggled);
			this.radioContactPersons.Toggled += new global::System.EventHandler (this.OnRadioContactPersonsToggled);
			this.radioContracts.Toggled += new global::System.EventHandler (this.OnRadioContractsToggled);
			this.radioDeliveryPoint.Toggled += new global::System.EventHandler (this.OnRadioDeliveryPointToggled);
			this.buttonDocFromLegal.Clicked += new global::System.EventHandler (this.OnButtonDocFromLegalClicked);
			this.buttonDocFromActual.Clicked += new global::System.EventHandler (this.OnButtonDocFromActualClicked);
			this.buttonActualFromLegal.Clicked += new global::System.EventHandler (this.OnButtonActualFromLegalClicked);
			this.yentrySignPost.FocusInEvent += new global::Gtk.FocusInEventHandler (this.OnYentrySignPostFocusInEvent);
			this.yentrySignBaseOf.FocusInEvent += new global::Gtk.FocusInEventHandler (this.OnYentrySignBaseOfFocusInEvent);
		}
	}
}
