
// This file has been generated by the GUI designer. Do not modify.
namespace BioGorod.Dialogs.Client
{
	public partial class CounterpartyDlg
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button buttonSave;
		
		private global::Gtk.Button buttonCancel;
		
		private global::QSFNS.GetOrgInfo getorginfo1;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.HBox hbox19;
		
		private global::Gtk.RadioButton radioInfo;
		
		private global::Gtk.RadioButton radioContactAndAddresses;
		
		private global::Gtk.RadioButton radioContracts;
		
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow4;
		
		private global::Gtk.VBox vbox10;
		
		private global::Gtk.Table table4;
		
		private global::Gamma.Widgets.yEnumComboBox comboDocumentsDelivery;
		
		private global::QSContacts.EmailsView emailsView;
		
		private global::Gamma.GtkWidgets.yEntry entryFullName;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow6;
		
		private global::Gamma.GtkWidgets.yTextView dataComment;
		
		private global::Gtk.HBox hbox13;
		
		private global::Gamma.GtkWidgets.yCheckButton ycheckIsArchived;
		
		private global::Gamma.GtkWidgets.yCheckButton checkHaveArbitration;
		
		private global::Gamma.GtkWidgets.yCheckButton checkRequirePrepayment;
		
		private global::Gtk.HBox hbox14;
		
		private global::Gamma.GtkWidgets.yEntry yentryInternalName;
		
		private global::Gtk.Button buttonNameToInternalName;
		
		private global::Gtk.HBox hbox18;
		
		private global::Gamma.GtkWidgets.yCheckButton ycheckContourFocus;
		
		private global::Gamma.GtkWidgets.yCheckButton ycheckMassRegistration;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.Button buttonActualFromLegal;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.Button buttonDocFromLegal;
		
		private global::Gtk.Button buttonDocFromActual;
		
		private global::QSOsm.JsonAddressEntry jsonaddressActual;
		
		private global::QSOsm.JsonAddressEntry jsonaddressDocDelivery;
		
		private global::QSOsm.JsonAddressEntry jsonaddressLegal;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.Label label18;
		
		private global::Gtk.Label label32;
		
		private global::Gtk.Label label35;
		
		private global::Gtk.Label label44;
		
		private global::Gtk.Label label46;
		
		private global::Gtk.Label label48;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Label label50;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.Label labelFullName;
		
		private global::Gtk.Label labelShort;
		
		private global::QSContacts.PhonesView phonesView;
		
		private global::Gamma.Widgets.yEntryReference referencePaymentManager;
		
		private global::Gtk.VBox vboxCooperation;
		
		private global::Gamma.GtkWidgets.yCheckButton checkCustomer;
		
		private global::Gamma.GtkWidgets.yCheckButton checkSupplier;
		
		private global::Gamma.GtkWidgets.yCheckButton checkPartner;
		
		private global::Gamma.Widgets.yDatePicker ydateCannotFind;
		
		private global::Gamma.GtkWidgets.yEntry yentryName;
		
		private global::Gtk.Table datatable4;
		
		private global::Gtk.Label label33;
		
		private global::Gtk.Label label37;
		
		private global::Gtk.Label label38;
		
		private global::Gtk.Label label39;
		
		private global::Gtk.Label label40;
		
		private global::Gtk.Label label41;
		
		private global::Gtk.Label label42;
		
		private global::Gamma.Widgets.yValidatedEntry validatedentryOGRN;
		
		private global::Gamma.Widgets.yValidatedEntry validatedINN;
		
		private global::Gamma.Widgets.yValidatedEntry validatedKPP;
		
		private global::Gamma.GtkWidgets.yEntry yentrySignBaseOf;
		
		private global::Gamma.GtkWidgets.yEntry yentrySignFIO;
		
		private global::Gamma.GtkWidgets.yEntry yentrySignFIOGenetivus;
		
		private global::Gamma.GtkWidgets.yEntry yentrySignPost;
		
		private global::QSBanks.AccountsView accountsView;
		
		private global::Gtk.Label label31;
		
		private global::Gtk.VBox vbox5;
		
		private global::BioGorod.Dialogs.Client.CounterpartyContactsView contactsview1;
		
		private global::BioGorod.Dialogs.Client.CounterpartyAddressesView deliveryPointView;
		
		private global::Gtk.Label label45;
		
		private global::BioGorod.Dialogs.Client.CounterpartyContractsView counterpartyContractsView;
		
		private global::Gtk.Label label47;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BioGorod.Dialogs.Client.CounterpartyDlg
			global::Stetic.BinContainer.Attach (this);
			this.Name = "BioGorod.Dialogs.Client.CounterpartyDlg";
			// Container child BioGorod.Dialogs.Client.CounterpartyDlg.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.HeightRequest = 400;
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(6));
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonSave = new global::Gtk.Button ();
			this.buttonSave.CanFocus = true;
			this.buttonSave.Name = "buttonSave";
			this.buttonSave.UseUnderline = true;
			this.buttonSave.Label = global::Mono.Unix.Catalog.GetString ("Сохранить");
			global::Gtk.Image w1 = new global::Gtk.Image ();
			w1.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-floppy", global::Gtk.IconSize.Menu);
			this.buttonSave.Image = w1;
			this.hbox1.Add (this.buttonSave);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonSave]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString ("Отмена");
			global::Gtk.Image w3 = new global::Gtk.Image ();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-revert-to-saved", global::Gtk.IconSize.Menu);
			this.buttonCancel.Image = w3;
			this.hbox1.Add (this.buttonCancel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonCancel]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.getorginfo1 = new global::QSFNS.GetOrgInfo ();
			this.getorginfo1.Events = ((global::Gdk.EventMask)(256));
			this.getorginfo1.Name = "getorginfo1";
			this.hbox1.Add (this.getorginfo1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.getorginfo1]));
			w5.Position = 2;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox2.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator1]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox19 = new global::Gtk.HBox ();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.radioInfo = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Информация"));
			this.radioInfo.CanFocus = true;
			this.radioInfo.Name = "radioInfo";
			this.radioInfo.DrawIndicator = false;
			this.radioInfo.UseUnderline = true;
			this.radioInfo.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.hbox19.Add (this.radioInfo);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.radioInfo]));
			w8.Position = 0;
			// Container child hbox19.Gtk.Box+BoxChild
			this.radioContactAndAddresses = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Адреса и контактные лица"));
			this.radioContactAndAddresses.CanFocus = true;
			this.radioContactAndAddresses.Name = "radioContactAndAddresses";
			this.radioContactAndAddresses.DrawIndicator = false;
			this.radioContactAndAddresses.UseUnderline = true;
			this.radioContactAndAddresses.Group = this.radioInfo.Group;
			this.hbox19.Add (this.radioContactAndAddresses);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.radioContactAndAddresses]));
			w9.Position = 1;
			// Container child hbox19.Gtk.Box+BoxChild
			this.radioContracts = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Договоры"));
			this.radioContracts.CanFocus = true;
			this.radioContracts.Name = "radioContracts";
			this.radioContracts.DrawIndicator = false;
			this.radioContracts.UseUnderline = true;
			this.radioContracts.Group = this.radioInfo.Group;
			this.hbox19.Add (this.radioContracts);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.radioContracts]));
			w10.Position = 2;
			this.vbox2.Add (this.hbox19);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox19]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
			this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
			global::Gtk.Viewport w12 = new global::Gtk.Viewport ();
			w12.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.table4 = new global::Gtk.Table (((uint)(13)), ((uint)(4)), false);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(6));
			this.table4.ColumnSpacing = ((uint)(6));
			this.table4.BorderWidth = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.comboDocumentsDelivery = new global::Gamma.Widgets.yEnumComboBox ();
			this.comboDocumentsDelivery.Name = "comboDocumentsDelivery";
			this.comboDocumentsDelivery.ShowSpecialStateAll = false;
			this.comboDocumentsDelivery.ShowSpecialStateNot = false;
			this.comboDocumentsDelivery.UseShortTitle = false;
			this.comboDocumentsDelivery.DefaultFirst = true;
			this.table4.Add (this.comboDocumentsDelivery);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table4 [this.comboDocumentsDelivery]));
			w13.TopAttach = ((uint)(5));
			w13.BottomAttach = ((uint)(6));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.emailsView = new global::QSContacts.EmailsView ();
			this.emailsView.Events = ((global::Gdk.EventMask)(256));
			this.emailsView.Name = "emailsView";
			this.table4.Add (this.emailsView);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table4 [this.emailsView]));
			w14.TopAttach = ((uint)(9));
			w14.BottomAttach = ((uint)(10));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(4));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.entryFullName = new global::Gamma.GtkWidgets.yEntry ();
			this.entryFullName.CanFocus = true;
			this.entryFullName.Name = "entryFullName";
			this.entryFullName.IsEditable = true;
			this.entryFullName.MaxLength = 300;
			this.entryFullName.InvisibleChar = '●';
			this.table4.Add (this.entryFullName);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table4 [this.entryFullName]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.GtkScrolledWindow6 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow6.Name = "GtkScrolledWindow6";
			this.GtkScrolledWindow6.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow6.Gtk.Container+ContainerChild
			this.dataComment = new global::Gamma.GtkWidgets.yTextView ();
			this.dataComment.CanFocus = true;
			this.dataComment.Name = "dataComment";
			this.GtkScrolledWindow6.Add (this.dataComment);
			this.table4.Add (this.GtkScrolledWindow6);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table4 [this.GtkScrolledWindow6]));
			w17.TopAttach = ((uint)(7));
			w17.BottomAttach = ((uint)(8));
			w17.LeftAttach = ((uint)(1));
			w17.RightAttach = ((uint)(4));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.hbox13 = new global::Gtk.HBox ();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.ycheckIsArchived = new global::Gamma.GtkWidgets.yCheckButton ();
			this.ycheckIsArchived.TooltipMarkup = "Больше не работаем с этим клиентом";
			this.ycheckIsArchived.CanFocus = true;
			this.ycheckIsArchived.Name = "ycheckIsArchived";
			this.ycheckIsArchived.Label = global::Mono.Unix.Catalog.GetString ("Архивный");
			this.ycheckIsArchived.DrawIndicator = true;
			this.ycheckIsArchived.UseUnderline = true;
			this.hbox13.Add (this.ycheckIsArchived);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.ycheckIsArchived]));
			w18.Position = 0;
			w18.Expand = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.checkHaveArbitration = new global::Gamma.GtkWidgets.yCheckButton ();
			this.checkHaveArbitration.CanFocus = true;
			this.checkHaveArbitration.Name = "checkHaveArbitration";
			this.checkHaveArbitration.Label = global::Mono.Unix.Catalog.GetString ("Есть арбитражные дела");
			this.checkHaveArbitration.DrawIndicator = true;
			this.checkHaveArbitration.UseUnderline = true;
			this.hbox13.Add (this.checkHaveArbitration);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.checkHaveArbitration]));
			w19.Position = 1;
			w19.Expand = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.checkRequirePrepayment = new global::Gamma.GtkWidgets.yCheckButton ();
			this.checkRequirePrepayment.CanFocus = true;
			this.checkRequirePrepayment.Name = "checkRequirePrepayment";
			this.checkRequirePrepayment.Label = global::Mono.Unix.Catalog.GetString ("Обязательна предоплата");
			this.checkRequirePrepayment.DrawIndicator = true;
			this.checkRequirePrepayment.UseUnderline = true;
			this.hbox13.Add (this.checkRequirePrepayment);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.checkRequirePrepayment]));
			w20.Position = 2;
			w20.Expand = false;
			this.table4.Add (this.hbox13);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table4 [this.hbox13]));
			w21.TopAttach = ((uint)(3));
			w21.BottomAttach = ((uint)(4));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(4));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.hbox14 = new global::Gtk.HBox ();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.yentryInternalName = new global::Gamma.GtkWidgets.yEntry ();
			this.yentryInternalName.CanFocus = true;
			this.yentryInternalName.Name = "yentryInternalName";
			this.yentryInternalName.IsEditable = true;
			this.yentryInternalName.MaxLength = 150;
			this.yentryInternalName.InvisibleChar = '●';
			this.hbox14.Add (this.yentryInternalName);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.yentryInternalName]));
			w22.Position = 0;
			// Container child hbox14.Gtk.Box+BoxChild
			this.buttonNameToInternalName = new global::Gtk.Button ();
			this.buttonNameToInternalName.CanFocus = true;
			this.buttonNameToInternalName.Name = "buttonNameToInternalName";
			this.buttonNameToInternalName.UseUnderline = true;
			this.buttonNameToInternalName.Label = global::Mono.Unix.Catalog.GetString ("Как наименование");
			this.hbox14.Add (this.buttonNameToInternalName);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.buttonNameToInternalName]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			this.table4.Add (this.hbox14);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table4 [this.hbox14]));
			w24.TopAttach = ((uint)(2));
			w24.BottomAttach = ((uint)(3));
			w24.LeftAttach = ((uint)(1));
			w24.RightAttach = ((uint)(4));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.hbox18 = new global::Gtk.HBox ();
			this.hbox18.Name = "hbox18";
			this.hbox18.Spacing = 6;
			// Container child hbox18.Gtk.Box+BoxChild
			this.ycheckContourFocus = new global::Gamma.GtkWidgets.yCheckButton ();
			this.ycheckContourFocus.CanFocus = true;
			this.ycheckContourFocus.Name = "ycheckContourFocus";
			this.ycheckContourFocus.Label = global::Mono.Unix.Catalog.GetString ("Проверка в Контур.Фокус");
			this.ycheckContourFocus.DrawIndicator = true;
			this.ycheckContourFocus.UseUnderline = true;
			this.hbox18.Add (this.ycheckContourFocus);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.ycheckContourFocus]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox18.Gtk.Box+BoxChild
			this.ycheckMassRegistration = new global::Gamma.GtkWidgets.yCheckButton ();
			this.ycheckMassRegistration.CanFocus = true;
			this.ycheckMassRegistration.Name = "ycheckMassRegistration";
			this.ycheckMassRegistration.Label = global::Mono.Unix.Catalog.GetString ("Адрес \"массовой\" регистрации");
			this.ycheckMassRegistration.DrawIndicator = true;
			this.ycheckMassRegistration.UseUnderline = true;
			this.hbox18.Add (this.ycheckMassRegistration);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.ycheckMassRegistration]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			this.table4.Add (this.hbox18);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table4 [this.hbox18]));
			w27.TopAttach = ((uint)(4));
			w27.BottomAttach = ((uint)(5));
			w27.LeftAttach = ((uint)(1));
			w27.RightAttach = ((uint)(2));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.buttonActualFromLegal = new global::Gtk.Button ();
			this.buttonActualFromLegal.TooltipMarkup = "Скопировать из юридического адреса.";
			this.buttonActualFromLegal.CanFocus = true;
			this.buttonActualFromLegal.Name = "buttonActualFromLegal";
			this.buttonActualFromLegal.UseUnderline = true;
			this.buttonActualFromLegal.Label = global::Mono.Unix.Catalog.GetString ("Как юридический");
			this.hbox7.Add (this.buttonActualFromLegal);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.buttonActualFromLegal]));
			w28.Position = 0;
			w28.Expand = false;
			w28.Fill = false;
			this.table4.Add (this.hbox7);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table4 [this.hbox7]));
			w29.TopAttach = ((uint)(11));
			w29.BottomAttach = ((uint)(12));
			w29.LeftAttach = ((uint)(3));
			w29.RightAttach = ((uint)(4));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table4.Gtk.Table+TableChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.buttonDocFromLegal = new global::Gtk.Button ();
			this.buttonDocFromLegal.TooltipMarkup = "Скопировать из юридического адреса.";
			this.buttonDocFromLegal.CanFocus = true;
			this.buttonDocFromLegal.Name = "buttonDocFromLegal";
			this.buttonDocFromLegal.UseUnderline = true;
			this.buttonDocFromLegal.Label = global::Mono.Unix.Catalog.GetString ("Как юридический");
			this.hbox8.Add (this.buttonDocFromLegal);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.buttonDocFromLegal]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.buttonDocFromActual = new global::Gtk.Button ();
			this.buttonDocFromActual.TooltipMarkup = "Скопировать из физического адреса.";
			this.buttonDocFromActual.CanFocus = true;
			this.buttonDocFromActual.Name = "buttonDocFromActual";
			this.buttonDocFromActual.UseUnderline = true;
			this.buttonDocFromActual.Label = global::Mono.Unix.Catalog.GetString ("Как фактический");
			this.hbox8.Add (this.buttonDocFromActual);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.buttonDocFromActual]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			this.table4.Add (this.hbox8);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table4 [this.hbox8]));
			w32.TopAttach = ((uint)(12));
			w32.BottomAttach = ((uint)(13));
			w32.LeftAttach = ((uint)(3));
			w32.RightAttach = ((uint)(4));
			w32.XOptions = ((global::Gtk.AttachOptions)(4));
			w32.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table4.Gtk.Table+TableChild
			this.jsonaddressActual = new global::QSOsm.JsonAddressEntry ();
			this.jsonaddressActual.Events = ((global::Gdk.EventMask)(256));
			this.jsonaddressActual.Name = "jsonaddressActual";
			this.jsonaddressActual.HideFloor = false;
			this.table4.Add (this.jsonaddressActual);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table4 [this.jsonaddressActual]));
			w33.TopAttach = ((uint)(11));
			w33.BottomAttach = ((uint)(12));
			w33.LeftAttach = ((uint)(1));
			w33.RightAttach = ((uint)(3));
			w33.XOptions = ((global::Gtk.AttachOptions)(4));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.jsonaddressDocDelivery = new global::QSOsm.JsonAddressEntry ();
			this.jsonaddressDocDelivery.Events = ((global::Gdk.EventMask)(256));
			this.jsonaddressDocDelivery.Name = "jsonaddressDocDelivery";
			this.jsonaddressDocDelivery.HideFloor = false;
			this.table4.Add (this.jsonaddressDocDelivery);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table4 [this.jsonaddressDocDelivery]));
			w34.TopAttach = ((uint)(12));
			w34.BottomAttach = ((uint)(13));
			w34.LeftAttach = ((uint)(1));
			w34.RightAttach = ((uint)(3));
			w34.XOptions = ((global::Gtk.AttachOptions)(4));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.jsonaddressLegal = new global::QSOsm.JsonAddressEntry ();
			this.jsonaddressLegal.Events = ((global::Gdk.EventMask)(256));
			this.jsonaddressLegal.Name = "jsonaddressLegal";
			this.jsonaddressLegal.HideFloor = true;
			this.table4.Add (this.jsonaddressLegal);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table4 [this.jsonaddressLegal]));
			w35.TopAttach = ((uint)(10));
			w35.BottomAttach = ((uint)(11));
			w35.LeftAttach = ((uint)(1));
			w35.RightAttach = ((uint)(3));
			w35.XOptions = ((global::Gtk.AttachOptions)(4));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xalign = 1F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Общий e-mail:");
			this.table4.Add (this.label11);
			global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table4 [this.label11]));
			w36.TopAttach = ((uint)(9));
			w36.BottomAttach = ((uint)(10));
			w36.XOptions = ((global::Gtk.AttachOptions)(4));
			w36.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.Xalign = 1F;
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Общие телефоны:");
			this.table4.Add (this.label18);
			global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table4 [this.label18]));
			w37.TopAttach = ((uint)(8));
			w37.BottomAttach = ((uint)(9));
			w37.XOptions = ((global::Gtk.AttachOptions)(4));
			w37.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label32 = new global::Gtk.Label ();
			this.label32.Name = "label32";
			this.label32.Xalign = 1F;
			this.label32.LabelProp = global::Mono.Unix.Catalog.GetString ("Не возможно разыскать c:");
			this.table4.Add (this.label32);
			global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table4 [this.label32]));
			w38.TopAttach = ((uint)(4));
			w38.BottomAttach = ((uint)(5));
			w38.LeftAttach = ((uint)(2));
			w38.RightAttach = ((uint)(3));
			w38.XOptions = ((global::Gtk.AttachOptions)(4));
			w38.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label35 = new global::Gtk.Label ();
			this.label35.Name = "label35";
			this.label35.Xalign = 1F;
			this.label35.LabelProp = global::Mono.Unix.Catalog.GetString ("Тип контрагента:");
			this.table4.Add (this.label35);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table4 [this.label35]));
			w39.TopAttach = ((uint)(5));
			w39.BottomAttach = ((uint)(6));
			w39.LeftAttach = ((uint)(2));
			w39.RightAttach = ((uint)(3));
			w39.XOptions = ((global::Gtk.AttachOptions)(4));
			w39.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label44 = new global::Gtk.Label ();
			this.label44.Name = "label44";
			this.label44.Xalign = 1F;
			this.label44.LabelProp = global::Mono.Unix.Catalog.GetString ("Ответственный за контроль оплаты:");
			this.table4.Add (this.label44);
			global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table4 [this.label44]));
			w40.TopAttach = ((uint)(6));
			w40.BottomAttach = ((uint)(7));
			w40.XOptions = ((global::Gtk.AttachOptions)(4));
			w40.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label46 = new global::Gtk.Label ();
			this.label46.Name = "label46";
			this.label46.Xalign = 1F;
			this.label46.Yalign = 0F;
			this.label46.LabelProp = global::Mono.Unix.Catalog.GetString ("Комментарий:");
			this.label46.Justify = ((global::Gtk.Justification)(1));
			this.table4.Add (this.label46);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table4 [this.label46]));
			w41.TopAttach = ((uint)(7));
			w41.BottomAttach = ((uint)(8));
			w41.XOptions = ((global::Gtk.AttachOptions)(4));
			w41.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label48 = new global::Gtk.Label ();
			this.label48.Name = "label48";
			this.label48.Xalign = 1F;
			this.label48.LabelProp = global::Mono.Unix.Catalog.GetString ("Как отправляем документы:");
			this.table4.Add (this.label48);
			global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table4 [this.label48]));
			w42.TopAttach = ((uint)(5));
			w42.BottomAttach = ((uint)(6));
			w42.XOptions = ((global::Gtk.AttachOptions)(4));
			w42.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 1F;
			this.label5.Yalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Юридический адрес:");
			this.table4.Add (this.label5);
			global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table4 [this.label5]));
			w43.TopAttach = ((uint)(10));
			w43.BottomAttach = ((uint)(11));
			w43.XOptions = ((global::Gtk.AttachOptions)(4));
			w43.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label50 = new global::Gtk.Label ();
			this.label50.Name = "label50";
			this.label50.Xalign = 1F;
			this.label50.LabelProp = global::Mono.Unix.Catalog.GetString ("Наименование для нас:");
			this.table4.Add (this.label50);
			global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table4 [this.label50]));
			w44.TopAttach = ((uint)(2));
			w44.BottomAttach = ((uint)(3));
			w44.XOptions = ((global::Gtk.AttachOptions)(4));
			w44.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 1F;
			this.label6.Yalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Фактический адрес:");
			this.table4.Add (this.label6);
			global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table4 [this.label6]));
			w45.TopAttach = ((uint)(11));
			w45.BottomAttach = ((uint)(12));
			w45.XOptions = ((global::Gtk.AttachOptions)(4));
			w45.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.Xalign = 1F;
			this.label8.Yalign = 0F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Адрес доставки документов:");
			this.table4.Add (this.label8);
			global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table4 [this.label8]));
			w46.TopAttach = ((uint)(12));
			w46.BottomAttach = ((uint)(13));
			w46.XOptions = ((global::Gtk.AttachOptions)(4));
			w46.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.labelFullName = new global::Gtk.Label ();
			this.labelFullName.Name = "labelFullName";
			this.labelFullName.Xalign = 1F;
			this.labelFullName.LabelProp = global::Mono.Unix.Catalog.GetString ("Полное наименование:");
			this.table4.Add (this.labelFullName);
			global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.table4 [this.labelFullName]));
			w47.TopAttach = ((uint)(1));
			w47.BottomAttach = ((uint)(2));
			w47.XOptions = ((global::Gtk.AttachOptions)(4));
			w47.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.labelShort = new global::Gtk.Label ();
			this.labelShort.Name = "labelShort";
			this.labelShort.Xalign = 1F;
			this.labelShort.LabelProp = global::Mono.Unix.Catalog.GetString ("Наименование:");
			this.table4.Add (this.labelShort);
			global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.table4 [this.labelShort]));
			w48.XOptions = ((global::Gtk.AttachOptions)(4));
			w48.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.phonesView = new global::QSContacts.PhonesView ();
			this.phonesView.Events = ((global::Gdk.EventMask)(256));
			this.phonesView.Name = "phonesView";
			this.table4.Add (this.phonesView);
			global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.table4 [this.phonesView]));
			w49.TopAttach = ((uint)(8));
			w49.BottomAttach = ((uint)(9));
			w49.LeftAttach = ((uint)(1));
			w49.RightAttach = ((uint)(4));
			w49.XOptions = ((global::Gtk.AttachOptions)(4));
			w49.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.referencePaymentManager = new global::Gamma.Widgets.yEntryReference ();
			this.referencePaymentManager.Events = ((global::Gdk.EventMask)(256));
			this.referencePaymentManager.Name = "referencePaymentManager";
			this.table4.Add (this.referencePaymentManager);
			global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.table4 [this.referencePaymentManager]));
			w50.TopAttach = ((uint)(6));
			w50.BottomAttach = ((uint)(7));
			w50.LeftAttach = ((uint)(1));
			w50.RightAttach = ((uint)(2));
			w50.XOptions = ((global::Gtk.AttachOptions)(4));
			w50.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.vboxCooperation = new global::Gtk.VBox ();
			this.vboxCooperation.Name = "vboxCooperation";
			this.vboxCooperation.Spacing = 1;
			// Container child vboxCooperation.Gtk.Box+BoxChild
			this.checkCustomer = new global::Gamma.GtkWidgets.yCheckButton ();
			this.checkCustomer.CanFocus = true;
			this.checkCustomer.Name = "checkCustomer";
			this.checkCustomer.Label = global::Mono.Unix.Catalog.GetString ("Покупатель");
			this.checkCustomer.DrawIndicator = true;
			this.checkCustomer.UseUnderline = true;
			this.vboxCooperation.Add (this.checkCustomer);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vboxCooperation [this.checkCustomer]));
			w51.Position = 0;
			w51.Expand = false;
			w51.Fill = false;
			// Container child vboxCooperation.Gtk.Box+BoxChild
			this.checkSupplier = new global::Gamma.GtkWidgets.yCheckButton ();
			this.checkSupplier.CanFocus = true;
			this.checkSupplier.Name = "checkSupplier";
			this.checkSupplier.Label = global::Mono.Unix.Catalog.GetString ("Поставщик");
			this.checkSupplier.DrawIndicator = true;
			this.checkSupplier.UseUnderline = true;
			this.vboxCooperation.Add (this.checkSupplier);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vboxCooperation [this.checkSupplier]));
			w52.Position = 1;
			w52.Expand = false;
			w52.Fill = false;
			// Container child vboxCooperation.Gtk.Box+BoxChild
			this.checkPartner = new global::Gamma.GtkWidgets.yCheckButton ();
			this.checkPartner.CanFocus = true;
			this.checkPartner.Name = "checkPartner";
			this.checkPartner.Label = global::Mono.Unix.Catalog.GetString ("Партнер");
			this.checkPartner.DrawIndicator = true;
			this.checkPartner.UseUnderline = true;
			this.vboxCooperation.Add (this.checkPartner);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vboxCooperation [this.checkPartner]));
			w53.Position = 2;
			w53.Expand = false;
			w53.Fill = false;
			this.table4.Add (this.vboxCooperation);
			global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.table4 [this.vboxCooperation]));
			w54.TopAttach = ((uint)(5));
			w54.BottomAttach = ((uint)(7));
			w54.LeftAttach = ((uint)(3));
			w54.RightAttach = ((uint)(4));
			w54.XOptions = ((global::Gtk.AttachOptions)(4));
			w54.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child table4.Gtk.Table+TableChild
			this.ydateCannotFind = new global::Gamma.Widgets.yDatePicker ();
			this.ydateCannotFind.Events = ((global::Gdk.EventMask)(256));
			this.ydateCannotFind.Name = "ydateCannotFind";
			this.ydateCannotFind.WithTime = false;
			this.ydateCannotFind.Date = new global::System.DateTime (0);
			this.ydateCannotFind.IsEditable = true;
			this.ydateCannotFind.AutoSeparation = true;
			this.table4.Add (this.ydateCannotFind);
			global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.table4 [this.ydateCannotFind]));
			w55.TopAttach = ((uint)(4));
			w55.BottomAttach = ((uint)(5));
			w55.LeftAttach = ((uint)(3));
			w55.RightAttach = ((uint)(4));
			w55.XOptions = ((global::Gtk.AttachOptions)(4));
			w55.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.yentryName = new global::Gamma.GtkWidgets.yEntry ();
			this.yentryName.CanFocus = true;
			this.yentryName.Name = "yentryName";
			this.yentryName.IsEditable = true;
			this.yentryName.MaxLength = 150;
			this.yentryName.InvisibleChar = '●';
			this.table4.Add (this.yentryName);
			global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.table4 [this.yentryName]));
			w56.LeftAttach = ((uint)(1));
			w56.RightAttach = ((uint)(4));
			w56.XOptions = ((global::Gtk.AttachOptions)(4));
			w56.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox10.Add (this.table4);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.table4]));
			w57.Position = 0;
			w57.Expand = false;
			w57.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.datatable4 = new global::Gtk.Table (((uint)(4)), ((uint)(4)), false);
			this.datatable4.Name = "datatable4";
			this.datatable4.RowSpacing = ((uint)(6));
			this.datatable4.ColumnSpacing = ((uint)(6));
			// Container child datatable4.Gtk.Table+TableChild
			this.label33 = new global::Gtk.Label ();
			this.label33.Name = "label33";
			this.label33.LabelProp = global::Mono.Unix.Catalog.GetString ("ФИО в родительном падеже:");
			this.datatable4.Add (this.label33);
			global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.label33]));
			w58.TopAttach = ((uint)(1));
			w58.BottomAttach = ((uint)(2));
			w58.LeftAttach = ((uint)(2));
			w58.RightAttach = ((uint)(3));
			w58.XOptions = ((global::Gtk.AttachOptions)(4));
			w58.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.label37 = new global::Gtk.Label ();
			this.label37.Name = "label37";
			this.label37.Xalign = 1F;
			this.label37.LabelProp = global::Mono.Unix.Catalog.GetString ("ИНН:");
			this.datatable4.Add (this.label37);
			global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.label37]));
			w59.XOptions = ((global::Gtk.AttachOptions)(4));
			w59.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.label38 = new global::Gtk.Label ();
			this.label38.Name = "label38";
			this.label38.Xalign = 1F;
			this.label38.LabelProp = global::Mono.Unix.Catalog.GetString ("В лице:");
			this.datatable4.Add (this.label38);
			global::Gtk.Table.TableChild w60 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.label38]));
			w60.TopAttach = ((uint)(2));
			w60.BottomAttach = ((uint)(3));
			w60.LeftAttach = ((uint)(2));
			w60.RightAttach = ((uint)(3));
			w60.XOptions = ((global::Gtk.AttachOptions)(4));
			w60.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.label39 = new global::Gtk.Label ();
			this.label39.Name = "label39";
			this.label39.Xalign = 1F;
			this.label39.LabelProp = global::Mono.Unix.Catalog.GetString ("ФИО директора:");
			this.datatable4.Add (this.label39);
			global::Gtk.Table.TableChild w61 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.label39]));
			w61.LeftAttach = ((uint)(2));
			w61.RightAttach = ((uint)(3));
			w61.XOptions = ((global::Gtk.AttachOptions)(4));
			w61.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.label40 = new global::Gtk.Label ();
			this.label40.Name = "label40";
			this.label40.Xalign = 1F;
			this.label40.LabelProp = global::Mono.Unix.Catalog.GetString ("КПП:");
			this.datatable4.Add (this.label40);
			global::Gtk.Table.TableChild w62 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.label40]));
			w62.TopAttach = ((uint)(1));
			w62.BottomAttach = ((uint)(2));
			w62.XOptions = ((global::Gtk.AttachOptions)(4));
			w62.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.label41 = new global::Gtk.Label ();
			this.label41.Name = "label41";
			this.label41.Xalign = 1F;
			this.label41.LabelProp = global::Mono.Unix.Catalog.GetString ("ОГРН:");
			this.datatable4.Add (this.label41);
			global::Gtk.Table.TableChild w63 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.label41]));
			w63.TopAttach = ((uint)(2));
			w63.BottomAttach = ((uint)(3));
			w63.XOptions = ((global::Gtk.AttachOptions)(4));
			w63.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.label42 = new global::Gtk.Label ();
			this.label42.Name = "label42";
			this.label42.Xalign = 1F;
			this.label42.LabelProp = global::Mono.Unix.Catalog.GetString ("На основании:");
			this.datatable4.Add (this.label42);
			global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.label42]));
			w64.TopAttach = ((uint)(3));
			w64.BottomAttach = ((uint)(4));
			w64.LeftAttach = ((uint)(2));
			w64.RightAttach = ((uint)(3));
			w64.XOptions = ((global::Gtk.AttachOptions)(4));
			w64.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.validatedentryOGRN = new global::Gamma.Widgets.yValidatedEntry ();
			this.validatedentryOGRN.CanFocus = true;
			this.validatedentryOGRN.Name = "validatedentryOGRN";
			this.validatedentryOGRN.IsEditable = true;
			this.validatedentryOGRN.MaxLength = 13;
			this.validatedentryOGRN.InvisibleChar = '●';
			this.datatable4.Add (this.validatedentryOGRN);
			global::Gtk.Table.TableChild w65 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.validatedentryOGRN]));
			w65.TopAttach = ((uint)(2));
			w65.BottomAttach = ((uint)(3));
			w65.LeftAttach = ((uint)(1));
			w65.RightAttach = ((uint)(2));
			w65.XOptions = ((global::Gtk.AttachOptions)(4));
			w65.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.validatedINN = new global::Gamma.Widgets.yValidatedEntry ();
			this.validatedINN.CanFocus = true;
			this.validatedINN.Name = "validatedINN";
			this.validatedINN.IsEditable = true;
			this.validatedINN.MaxLength = 12;
			this.validatedINN.InvisibleChar = '●';
			this.datatable4.Add (this.validatedINN);
			global::Gtk.Table.TableChild w66 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.validatedINN]));
			w66.LeftAttach = ((uint)(1));
			w66.RightAttach = ((uint)(2));
			w66.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.validatedKPP = new global::Gamma.Widgets.yValidatedEntry ();
			this.validatedKPP.CanFocus = true;
			this.validatedKPP.Name = "validatedKPP";
			this.validatedKPP.IsEditable = true;
			this.validatedKPP.MaxLength = 9;
			this.validatedKPP.InvisibleChar = '●';
			this.datatable4.Add (this.validatedKPP);
			global::Gtk.Table.TableChild w67 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.validatedKPP]));
			w67.TopAttach = ((uint)(1));
			w67.BottomAttach = ((uint)(2));
			w67.LeftAttach = ((uint)(1));
			w67.RightAttach = ((uint)(2));
			w67.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.yentrySignBaseOf = new global::Gamma.GtkWidgets.yEntry ();
			this.yentrySignBaseOf.CanFocus = true;
			this.yentrySignBaseOf.Name = "yentrySignBaseOf";
			this.yentrySignBaseOf.IsEditable = true;
			this.yentrySignBaseOf.InvisibleChar = '●';
			this.datatable4.Add (this.yentrySignBaseOf);
			global::Gtk.Table.TableChild w68 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.yentrySignBaseOf]));
			w68.TopAttach = ((uint)(3));
			w68.BottomAttach = ((uint)(4));
			w68.LeftAttach = ((uint)(3));
			w68.RightAttach = ((uint)(4));
			w68.XOptions = ((global::Gtk.AttachOptions)(4));
			w68.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.yentrySignFIO = new global::Gamma.GtkWidgets.yEntry ();
			this.yentrySignFIO.CanFocus = true;
			this.yentrySignFIO.Name = "yentrySignFIO";
			this.yentrySignFIO.IsEditable = true;
			this.yentrySignFIO.InvisibleChar = '●';
			this.datatable4.Add (this.yentrySignFIO);
			global::Gtk.Table.TableChild w69 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.yentrySignFIO]));
			w69.LeftAttach = ((uint)(3));
			w69.RightAttach = ((uint)(4));
			w69.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.yentrySignFIOGenetivus = new global::Gamma.GtkWidgets.yEntry ();
			this.yentrySignFIOGenetivus.CanFocus = true;
			this.yentrySignFIOGenetivus.Name = "yentrySignFIOGenetivus";
			this.yentrySignFIOGenetivus.IsEditable = true;
			this.yentrySignFIOGenetivus.MaxLength = 100;
			this.yentrySignFIOGenetivus.InvisibleChar = '●';
			this.datatable4.Add (this.yentrySignFIOGenetivus);
			global::Gtk.Table.TableChild w70 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.yentrySignFIOGenetivus]));
			w70.TopAttach = ((uint)(1));
			w70.BottomAttach = ((uint)(2));
			w70.LeftAttach = ((uint)(3));
			w70.RightAttach = ((uint)(4));
			w70.XOptions = ((global::Gtk.AttachOptions)(4));
			w70.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable4.Gtk.Table+TableChild
			this.yentrySignPost = new global::Gamma.GtkWidgets.yEntry ();
			this.yentrySignPost.CanFocus = true;
			this.yentrySignPost.Name = "yentrySignPost";
			this.yentrySignPost.IsEditable = true;
			this.yentrySignPost.InvisibleChar = '●';
			this.datatable4.Add (this.yentrySignPost);
			global::Gtk.Table.TableChild w71 = ((global::Gtk.Table.TableChild)(this.datatable4 [this.yentrySignPost]));
			w71.TopAttach = ((uint)(2));
			w71.BottomAttach = ((uint)(3));
			w71.LeftAttach = ((uint)(3));
			w71.RightAttach = ((uint)(4));
			w71.XOptions = ((global::Gtk.AttachOptions)(4));
			w71.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox10.Add (this.datatable4);
			global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.datatable4]));
			w72.Position = 1;
			w72.Expand = false;
			w72.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.accountsView = new global::QSBanks.AccountsView ();
			this.accountsView.Events = ((global::Gdk.EventMask)(256));
			this.accountsView.Name = "accountsView";
			this.vbox10.Add (this.accountsView);
			global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.accountsView]));
			w73.Position = 2;
			w12.Add (this.vbox10);
			this.GtkScrolledWindow4.Add (w12);
			this.notebook1.Add (this.GtkScrolledWindow4);
			// Notebook tab
			this.label31 = new global::Gtk.Label ();
			this.label31.Name = "label31";
			this.label31.LabelProp = global::Mono.Unix.Catalog.GetString ("Информация");
			this.notebook1.SetTabLabel (this.GtkScrolledWindow4, this.label31);
			this.label31.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.contactsview1 = new global::BioGorod.Dialogs.Client.CounterpartyContactsView ();
			this.contactsview1.Events = ((global::Gdk.EventMask)(256));
			this.contactsview1.Name = "contactsview1";
			this.vbox5.Add (this.contactsview1);
			global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.contactsview1]));
			w77.Position = 0;
			// Container child vbox5.Gtk.Box+BoxChild
			this.deliveryPointView = new global::BioGorod.Dialogs.Client.CounterpartyAddressesView ();
			this.deliveryPointView.Events = ((global::Gdk.EventMask)(256));
			this.deliveryPointView.Name = "deliveryPointView";
			this.vbox5.Add (this.deliveryPointView);
			global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.deliveryPointView]));
			w78.Position = 1;
			this.notebook1.Add (this.vbox5);
			global::Gtk.Notebook.NotebookChild w79 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox5]));
			w79.Position = 1;
			// Notebook tab
			this.label45 = new global::Gtk.Label ();
			this.label45.Name = "label45";
			this.label45.LabelProp = global::Mono.Unix.Catalog.GetString ("Контактные лица");
			this.notebook1.SetTabLabel (this.vbox5, this.label45);
			this.label45.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.counterpartyContractsView = new global::BioGorod.Dialogs.Client.CounterpartyContractsView ();
			this.counterpartyContractsView.Events = ((global::Gdk.EventMask)(256));
			this.counterpartyContractsView.Name = "counterpartyContractsView";
			this.notebook1.Add (this.counterpartyContractsView);
			global::Gtk.Notebook.NotebookChild w80 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.counterpartyContractsView]));
			w80.Position = 2;
			// Notebook tab
			this.label47 = new global::Gtk.Label ();
			this.label47.Name = "label47";
			this.label47.LabelProp = global::Mono.Unix.Catalog.GetString ("Договор");
			this.notebook1.SetTabLabel (this.counterpartyContractsView, this.label47);
			this.label47.ShowAll ();
			this.vbox2.Add (this.notebook1);
			global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.notebook1]));
			w81.Position = 3;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.buttonSave.Clicked += new global::System.EventHandler (this.OnButtonSaveClicked);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
			this.getorginfo1.FillButtonCliked += new global::System.EventHandler (this.OnGetorginfo1FillButtonCliked);
			this.radioInfo.Toggled += new global::System.EventHandler (this.OnRadioInfoToggled);
			this.radioContactAndAddresses.Toggled += new global::System.EventHandler (this.OnRadioContactPersonsToggled);
			this.radioContracts.Toggled += new global::System.EventHandler (this.OnRadioContractsToggled);
			this.buttonDocFromLegal.Clicked += new global::System.EventHandler (this.OnButtonDocFromLegalClicked);
			this.buttonDocFromActual.Clicked += new global::System.EventHandler (this.OnButtonDocFromActualClicked);
			this.buttonActualFromLegal.Clicked += new global::System.EventHandler (this.OnButtonActualFromLegalClicked);
			this.buttonNameToInternalName.Clicked += new global::System.EventHandler (this.OnButtonNameToInternalNameClicked);
			this.yentrySignPost.FocusInEvent += new global::Gtk.FocusInEventHandler (this.OnYentrySignPostFocusInEvent);
			this.yentrySignBaseOf.FocusInEvent += new global::Gtk.FocusInEventHandler (this.OnYentrySignBaseOfFocusInEvent);
		}
	}
}
